name: doc_renewal_reminder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  add_2_calendar: ^3.0.0
  share_plus: ^7.2.2
  file_picker: ^10.3.8
  local_auth: ^2.1.8
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_intl:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - lib/core/localization/
    - assets/icons/

  generate: true